theme: jekyll-theme-minimal
title: Pavel Zaitsau
description: Team Leader | Scrum Master | Senior Software Engineer
logo: http://gravatar.com/avatar/a372847419deaffe3aa784fb1fb14e2e?s=1000
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
